### ISSUE TITLE
problem with yarn package

### ISSUE THREAD

**Issue by cadot-eu** [tahir-sharif/sortable-draggable-js#1]
Thanks for your projetc, i's clean and fast.
i use symfony 6 ant webpack/encore.
if i use `yarn add sortable-draggable-js`
and `import Sortable from 'sortable-dnd'` i have a error.
I have see the nodes-modules, i have package.json, minified.js and README.
If i clone the git, i have no problem by `import Sortable from './sortable-draggable-js/package/sortable.js';` or ...minified.js
and no problem with yarn by `import Sortable from 'sortable-draggable-js/minified.js';`

**Comment by tahir-sharif** [comment]
Hi @cadot-eu ,

Thank you so much for using sortable-draggable-js and for reporting the issue!

I've investigated the problem and found that the entry point of the package was incorrectly configured in the package.json file, which caused the error when importing via yarn add. I'm happy to let you know that I've corrected the entry point, and the issue should now be resolved.

Please update your package by running:

```bash
yarn upgrade sortable-draggable-js
```

This should allow you to import it without any issues:

```javascript
import Sortable from 'sortable-dnd';
```

If you run into any further problems or have any more feedback, feel free to let me know. I really appreciate your patience and support in improving the library!

Best regards,
Tahir
